WebApplication3/WebApplication3/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class TestController : Controller
    {
        productdbEntities ddEntity = null;
        // GET: Test
        public ActionResult Index()
        {
            ddEntity = new productdbEntities();
           var data  =  ddEntity.PRODUCTs.ToArray();
            return View(data);
        }
        public ActionResult Edit(int? id)
        {
            ddEntity = new productdbEntities();
            var data = ddEntity.PRODUCTs.Where(x => x.ID == id).ToArray();
            return View(data);
        }

        [HttpPost]
        public ActionResult Save(int? id)
        {
            int id01 = int.Parse(Request.Form["id"].ToString());
            ddEntity = new productdbEntities();
            var data = ddEntity.PRODUCTs.Where(x => x.ID == id01).SingleOrDefault();
            data.PRO_NAME = Request.Form["prodctName"].ToString();
            ddEntity.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebApplication3/WebApplication3/Views/Test/Edit.cshtml
@model IEnumerable<WebApplication3.PRODUCT>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table">

    <tr>
        <td>PRODUCT NAME</td>
        <td> QUANTITY</td>
    </tr>
    
</table>

@using (Html.BeginForm("Save", "Test", FormMethod.Post))
{
foreach (var item in Model)
{


    <tr>
        <input type="hidden" name="id" value="@item.ID" class="form-control" />
        <td><input type="text" name="prodctName" value="@item.PRO_NAME" class="form-control" /></td>
        <td> @item.PRO_QT</td>
        <td><input type="submit" name="Save" value="Save" class="btn btn-danger" />
       </td>
    </tr>
}
   
}

WebApplication3/WebApplication3/Views/Test/Index.cshtml
@model IEnumerable<WebApplication3.PRODUCT>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table">

    <tr>
        <td>PRODUCT NAME</td>
        <td> QUANTITY</td>
    </tr>
    @foreach (var item in Model)
    {

    
    <tr>
        <td>@item.PRO_NAME</td>
        <td> @item.PRO_QT</td>
        <td>@Html.ActionLink("Edit", "Edit", "Test", new { @id = item.ID}, new { @class = "" })</td>
    </tr>
    }
</table>

WebApplication3/WebApplication3/Views/Test/Save.cshtml
@{
    ViewBag.Title = "Save";
}

<h2>Save</h2>